name: Build PHP 8 Image
on:
  workflow_dispatch:
    inputs:
      php82Version:
        description: "PHP 8.2 Version"
        default: "8.2.20"
        required: true
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build PHP-8.2 and Push
        uses: docker/build-push-action@v5
        with:
          context: php/8
          file: php/8/Dockerfile
          platforms: linux/amd64,linux/arm/v7,linux/arm64/v8,linux/s390x
          push: true
          build-args: PHP_VERSION=${{ github.event.inputs.php82Version }}
          tags: |
            1alin/php:${{ github.event.inputs.php82Version }}-fpm
        #   cache-from: type=gha
        #   cache-to: type=gha,mode=max
